package models

type User struct {
	Poc_Lead                                string
	Point_of_contact                        string
	Employee_Id                             string
	Full_Name                               string
	Company                                 string
	Unit                                    string
	Department                              string
	Section                                 string
	Job_Category                            string
	Designation                             string
	Employee_Type                           string
	Work_Location                           string
	Reporting_Employee_ID                   string
	Reporting_Employee_Name                 string
	Reporting_Designation                   string
	Gender                                  string
	Religion                                string
	National_id                             string
	Name                                    string
	Date_of_Birth                           string
	Father_name                             string
	Mother_Name                             string
	Blood                                   string
	Personal_Phone                          string
	Present_Address                         string
	Permanent_Address                       string
	Marital_Status                          string
	Emergency_Contact_name                  string
	Emergency_Contact_Relation              string
	Emergency_Contact_Address               string
	Emergency_Contact_Phone                 string
	Personal_Email                          string
	Tin_No                                  string
	Tin_Circle                              string
	Tin_Zone                                string
	Employee_Office_Mobile                  string
	Employee_Office_Email                   string
	Education_Secondary_Institute           string
	Education_Secondary_Major               string
	Education_Secondary_Institution         string
	Education_Secondary_Result              string
	Education_Secondary_Passing_Year        string
	Education_Higher_Secondary_Institute    string
	Education_Higher_Secondary_Major        string
	Education_Higher_Secondary_Institution  string
	Education_Higher_Secondary_Result       string
	Education_Higher_Secondary_Passing_Year string
	Education_Graduation_Institute          string
	Education_Graduation_Major              string
	Education_Graduation_Institution        string
	Education_Graduation_Result             string
	Education_Graduation_Passing_Year       string
	Education_POST_Graduation_Institute     string
	Education_POST_Graduation_Major         string
	Education_POST_Graduation_Institution   string
	Education_POST_Graduation_Result        string
	Education_POST_Graduation_Passing_Year  string
	Work_Experience_First_Name              string
	Work_Experience_First_Designation       string
	Work_Experience_First_Date_To           string
	Work_Experience_First_Date_From         string
	Work_Experience_Second_Name             string
	Work_Experience_Second_Designation      string
	Work_Experience_Second_Date_To          string
	Work_Experience_Second_Date_From        string
	Work_Experience_Third_Name              string
	Work_Experience_Third_Designation       string
	Work_Experience_Third_Date_To           string
	Work_Experience_Third_Date_From         string
	Work_Experience_Fourth_Name             string
	Work_Experience_Fourth_Designation      string
	Work_Experience_Fourth_Date_To          string
	Work_Experience_Fourth_Date_From        string
	Work_Experience_Fifth_Name              string
	Work_Experience_Fifth_Designation       string
	Work_Experience_Fifth_Date_To           string
	Work_Experience_Fifth_Date_From         string
	Work_Experience_Sixth_Name              string
	Work_Experience_Sixth_Designation       string
	Work_Experience_Sixth_Date_To           string
	Work_Experience_Sixth_Date_From         string
}
